volumes:
  pg_data:

services:

  db:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8000:8000"
    env_file: ../.env
    depends_on:
      - db

