"""Phone field 16 length

Revision ID: d63480f47ad8
Revises: 013af8d43489
Create Date: 2025-05-15 14:27:43.473663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd63480f47ad8'
down_revision: Union[str, None] = '013af8d43489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)
    # ### end Alembic commands ###
